// Cloud Agent Platform — TaskService API
//
// This service defines the core task management operations for the Cloud Agent Platform.
// All capabilities are exposed via MCP Tools; REST API is an equivalent HTTP translation layer.

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: task.proto

package capv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/cloud-agent-platform/cap/api/cap/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// TaskServiceName is the fully-qualified name of the TaskService service.
	TaskServiceName = "cap.v1.TaskService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// TaskServiceSubmitProcedure is the fully-qualified name of the TaskService's Submit RPC.
	TaskServiceSubmitProcedure = "/cap.v1.TaskService/Submit"
	// TaskServiceGetProcedure is the fully-qualified name of the TaskService's Get RPC.
	TaskServiceGetProcedure = "/cap.v1.TaskService/Get"
	// TaskServiceListProcedure is the fully-qualified name of the TaskService's List RPC.
	TaskServiceListProcedure = "/cap.v1.TaskService/List"
	// TaskServiceCancelProcedure is the fully-qualified name of the TaskService's Cancel RPC.
	TaskServiceCancelProcedure = "/cap.v1.TaskService/Cancel"
	// TaskServiceDecideProcedure is the fully-qualified name of the TaskService's Decide RPC.
	TaskServiceDecideProcedure = "/cap.v1.TaskService/Decide"
	// TaskServiceGetArtifactProcedure is the fully-qualified name of the TaskService's GetArtifact RPC.
	TaskServiceGetArtifactProcedure = "/cap.v1.TaskService/GetArtifact"
	// TaskServiceGetDiffProcedure is the fully-qualified name of the TaskService's GetDiff RPC.
	TaskServiceGetDiffProcedure = "/cap.v1.TaskService/GetDiff"
	// TaskServiceWaitProcedure is the fully-qualified name of the TaskService's Wait RPC.
	TaskServiceWaitProcedure = "/cap.v1.TaskService/Wait"
)

// TaskServiceClient is a client for the cap.v1.TaskService service.
type TaskServiceClient interface {
	// Submit a new task for execution.
	Submit(context.Context, *connect.Request[v1.SubmitTaskRequest]) (*connect.Response[v1.SubmitTaskResponse], error)
	// Get returns the current state of a task.
	Get(context.Context, *connect.Request[v1.GetTaskRequest]) (*connect.Response[v1.GetTaskResponse], error)
	// List returns a paginated list of tasks.
	List(context.Context, *connect.Request[v1.ListTasksRequest]) (*connect.Response[v1.ListTasksResponse], error)
	// Cancel cancels a running or pending task.
	Cancel(context.Context, *connect.Request[v1.CancelTaskRequest]) (*connect.Response[v1.CancelTaskResponse], error)
	// Decide submits a user decision for a confirmation request.
	Decide(context.Context, *connect.Request[v1.DecideRequest]) (*connect.Response[v1.DecideResponse], error)
	// GetArtifact retrieves a task artifact by ID.
	GetArtifact(context.Context, *connect.Request[v1.GetArtifactRequest]) (*connect.Response[v1.GetArtifactResponse], error)
	// GetDiff returns the code diff for a task.
	GetDiff(context.Context, *connect.Request[v1.GetDiffRequest]) (*connect.Response[v1.GetDiffResponse], error)
	// Wait blocks until the task is complete or confirmation is required.
	Wait(context.Context, *connect.Request[v1.WaitTaskRequest]) (*connect.Response[v1.WaitTaskResponse], error)
}

// NewTaskServiceClient constructs a client for the cap.v1.TaskService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewTaskServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) TaskServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	taskServiceMethods := v1.File_task_proto.Services().ByName("TaskService").Methods()
	return &taskServiceClient{
		submit: connect.NewClient[v1.SubmitTaskRequest, v1.SubmitTaskResponse](
			httpClient,
			baseURL+TaskServiceSubmitProcedure,
			connect.WithSchema(taskServiceMethods.ByName("Submit")),
			connect.WithClientOptions(opts...),
		),
		get: connect.NewClient[v1.GetTaskRequest, v1.GetTaskResponse](
			httpClient,
			baseURL+TaskServiceGetProcedure,
			connect.WithSchema(taskServiceMethods.ByName("Get")),
			connect.WithClientOptions(opts...),
		),
		list: connect.NewClient[v1.ListTasksRequest, v1.ListTasksResponse](
			httpClient,
			baseURL+TaskServiceListProcedure,
			connect.WithSchema(taskServiceMethods.ByName("List")),
			connect.WithClientOptions(opts...),
		),
		cancel: connect.NewClient[v1.CancelTaskRequest, v1.CancelTaskResponse](
			httpClient,
			baseURL+TaskServiceCancelProcedure,
			connect.WithSchema(taskServiceMethods.ByName("Cancel")),
			connect.WithClientOptions(opts...),
		),
		decide: connect.NewClient[v1.DecideRequest, v1.DecideResponse](
			httpClient,
			baseURL+TaskServiceDecideProcedure,
			connect.WithSchema(taskServiceMethods.ByName("Decide")),
			connect.WithClientOptions(opts...),
		),
		getArtifact: connect.NewClient[v1.GetArtifactRequest, v1.GetArtifactResponse](
			httpClient,
			baseURL+TaskServiceGetArtifactProcedure,
			connect.WithSchema(taskServiceMethods.ByName("GetArtifact")),
			connect.WithClientOptions(opts...),
		),
		getDiff: connect.NewClient[v1.GetDiffRequest, v1.GetDiffResponse](
			httpClient,
			baseURL+TaskServiceGetDiffProcedure,
			connect.WithSchema(taskServiceMethods.ByName("GetDiff")),
			connect.WithClientOptions(opts...),
		),
		wait: connect.NewClient[v1.WaitTaskRequest, v1.WaitTaskResponse](
			httpClient,
			baseURL+TaskServiceWaitProcedure,
			connect.WithSchema(taskServiceMethods.ByName("Wait")),
			connect.WithClientOptions(opts...),
		),
	}
}

// taskServiceClient implements TaskServiceClient.
type taskServiceClient struct {
	submit      *connect.Client[v1.SubmitTaskRequest, v1.SubmitTaskResponse]
	get         *connect.Client[v1.GetTaskRequest, v1.GetTaskResponse]
	list        *connect.Client[v1.ListTasksRequest, v1.ListTasksResponse]
	cancel      *connect.Client[v1.CancelTaskRequest, v1.CancelTaskResponse]
	decide      *connect.Client[v1.DecideRequest, v1.DecideResponse]
	getArtifact *connect.Client[v1.GetArtifactRequest, v1.GetArtifactResponse]
	getDiff     *connect.Client[v1.GetDiffRequest, v1.GetDiffResponse]
	wait        *connect.Client[v1.WaitTaskRequest, v1.WaitTaskResponse]
}

// Submit calls cap.v1.TaskService.Submit.
func (c *taskServiceClient) Submit(ctx context.Context, req *connect.Request[v1.SubmitTaskRequest]) (*connect.Response[v1.SubmitTaskResponse], error) {
	return c.submit.CallUnary(ctx, req)
}

// Get calls cap.v1.TaskService.Get.
func (c *taskServiceClient) Get(ctx context.Context, req *connect.Request[v1.GetTaskRequest]) (*connect.Response[v1.GetTaskResponse], error) {
	return c.get.CallUnary(ctx, req)
}

// List calls cap.v1.TaskService.List.
func (c *taskServiceClient) List(ctx context.Context, req *connect.Request[v1.ListTasksRequest]) (*connect.Response[v1.ListTasksResponse], error) {
	return c.list.CallUnary(ctx, req)
}

// Cancel calls cap.v1.TaskService.Cancel.
func (c *taskServiceClient) Cancel(ctx context.Context, req *connect.Request[v1.CancelTaskRequest]) (*connect.Response[v1.CancelTaskResponse], error) {
	return c.cancel.CallUnary(ctx, req)
}

// Decide calls cap.v1.TaskService.Decide.
func (c *taskServiceClient) Decide(ctx context.Context, req *connect.Request[v1.DecideRequest]) (*connect.Response[v1.DecideResponse], error) {
	return c.decide.CallUnary(ctx, req)
}

// GetArtifact calls cap.v1.TaskService.GetArtifact.
func (c *taskServiceClient) GetArtifact(ctx context.Context, req *connect.Request[v1.GetArtifactRequest]) (*connect.Response[v1.GetArtifactResponse], error) {
	return c.getArtifact.CallUnary(ctx, req)
}

// GetDiff calls cap.v1.TaskService.GetDiff.
func (c *taskServiceClient) GetDiff(ctx context.Context, req *connect.Request[v1.GetDiffRequest]) (*connect.Response[v1.GetDiffResponse], error) {
	return c.getDiff.CallUnary(ctx, req)
}

// Wait calls cap.v1.TaskService.Wait.
func (c *taskServiceClient) Wait(ctx context.Context, req *connect.Request[v1.WaitTaskRequest]) (*connect.Response[v1.WaitTaskResponse], error) {
	return c.wait.CallUnary(ctx, req)
}

// TaskServiceHandler is an implementation of the cap.v1.TaskService service.
type TaskServiceHandler interface {
	// Submit a new task for execution.
	Submit(context.Context, *connect.Request[v1.SubmitTaskRequest]) (*connect.Response[v1.SubmitTaskResponse], error)
	// Get returns the current state of a task.
	Get(context.Context, *connect.Request[v1.GetTaskRequest]) (*connect.Response[v1.GetTaskResponse], error)
	// List returns a paginated list of tasks.
	List(context.Context, *connect.Request[v1.ListTasksRequest]) (*connect.Response[v1.ListTasksResponse], error)
	// Cancel cancels a running or pending task.
	Cancel(context.Context, *connect.Request[v1.CancelTaskRequest]) (*connect.Response[v1.CancelTaskResponse], error)
	// Decide submits a user decision for a confirmation request.
	Decide(context.Context, *connect.Request[v1.DecideRequest]) (*connect.Response[v1.DecideResponse], error)
	// GetArtifact retrieves a task artifact by ID.
	GetArtifact(context.Context, *connect.Request[v1.GetArtifactRequest]) (*connect.Response[v1.GetArtifactResponse], error)
	// GetDiff returns the code diff for a task.
	GetDiff(context.Context, *connect.Request[v1.GetDiffRequest]) (*connect.Response[v1.GetDiffResponse], error)
	// Wait blocks until the task is complete or confirmation is required.
	Wait(context.Context, *connect.Request[v1.WaitTaskRequest]) (*connect.Response[v1.WaitTaskResponse], error)
}

// NewTaskServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewTaskServiceHandler(svc TaskServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	taskServiceMethods := v1.File_task_proto.Services().ByName("TaskService").Methods()
	taskServiceSubmitHandler := connect.NewUnaryHandler(
		TaskServiceSubmitProcedure,
		svc.Submit,
		connect.WithSchema(taskServiceMethods.ByName("Submit")),
		connect.WithHandlerOptions(opts...),
	)
	taskServiceGetHandler := connect.NewUnaryHandler(
		TaskServiceGetProcedure,
		svc.Get,
		connect.WithSchema(taskServiceMethods.ByName("Get")),
		connect.WithHandlerOptions(opts...),
	)
	taskServiceListHandler := connect.NewUnaryHandler(
		TaskServiceListProcedure,
		svc.List,
		connect.WithSchema(taskServiceMethods.ByName("List")),
		connect.WithHandlerOptions(opts...),
	)
	taskServiceCancelHandler := connect.NewUnaryHandler(
		TaskServiceCancelProcedure,
		svc.Cancel,
		connect.WithSchema(taskServiceMethods.ByName("Cancel")),
		connect.WithHandlerOptions(opts...),
	)
	taskServiceDecideHandler := connect.NewUnaryHandler(
		TaskServiceDecideProcedure,
		svc.Decide,
		connect.WithSchema(taskServiceMethods.ByName("Decide")),
		connect.WithHandlerOptions(opts...),
	)
	taskServiceGetArtifactHandler := connect.NewUnaryHandler(
		TaskServiceGetArtifactProcedure,
		svc.GetArtifact,
		connect.WithSchema(taskServiceMethods.ByName("GetArtifact")),
		connect.WithHandlerOptions(opts...),
	)
	taskServiceGetDiffHandler := connect.NewUnaryHandler(
		TaskServiceGetDiffProcedure,
		svc.GetDiff,
		connect.WithSchema(taskServiceMethods.ByName("GetDiff")),
		connect.WithHandlerOptions(opts...),
	)
	taskServiceWaitHandler := connect.NewUnaryHandler(
		TaskServiceWaitProcedure,
		svc.Wait,
		connect.WithSchema(taskServiceMethods.ByName("Wait")),
		connect.WithHandlerOptions(opts...),
	)
	return "/cap.v1.TaskService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case TaskServiceSubmitProcedure:
			taskServiceSubmitHandler.ServeHTTP(w, r)
		case TaskServiceGetProcedure:
			taskServiceGetHandler.ServeHTTP(w, r)
		case TaskServiceListProcedure:
			taskServiceListHandler.ServeHTTP(w, r)
		case TaskServiceCancelProcedure:
			taskServiceCancelHandler.ServeHTTP(w, r)
		case TaskServiceDecideProcedure:
			taskServiceDecideHandler.ServeHTTP(w, r)
		case TaskServiceGetArtifactProcedure:
			taskServiceGetArtifactHandler.ServeHTTP(w, r)
		case TaskServiceGetDiffProcedure:
			taskServiceGetDiffHandler.ServeHTTP(w, r)
		case TaskServiceWaitProcedure:
			taskServiceWaitHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedTaskServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedTaskServiceHandler struct{}

func (UnimplementedTaskServiceHandler) Submit(context.Context, *connect.Request[v1.SubmitTaskRequest]) (*connect.Response[v1.SubmitTaskResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cap.v1.TaskService.Submit is not implemented"))
}

func (UnimplementedTaskServiceHandler) Get(context.Context, *connect.Request[v1.GetTaskRequest]) (*connect.Response[v1.GetTaskResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cap.v1.TaskService.Get is not implemented"))
}

func (UnimplementedTaskServiceHandler) List(context.Context, *connect.Request[v1.ListTasksRequest]) (*connect.Response[v1.ListTasksResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cap.v1.TaskService.List is not implemented"))
}

func (UnimplementedTaskServiceHandler) Cancel(context.Context, *connect.Request[v1.CancelTaskRequest]) (*connect.Response[v1.CancelTaskResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cap.v1.TaskService.Cancel is not implemented"))
}

func (UnimplementedTaskServiceHandler) Decide(context.Context, *connect.Request[v1.DecideRequest]) (*connect.Response[v1.DecideResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cap.v1.TaskService.Decide is not implemented"))
}

func (UnimplementedTaskServiceHandler) GetArtifact(context.Context, *connect.Request[v1.GetArtifactRequest]) (*connect.Response[v1.GetArtifactResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cap.v1.TaskService.GetArtifact is not implemented"))
}

func (UnimplementedTaskServiceHandler) GetDiff(context.Context, *connect.Request[v1.GetDiffRequest]) (*connect.Response[v1.GetDiffResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cap.v1.TaskService.GetDiff is not implemented"))
}

func (UnimplementedTaskServiceHandler) Wait(context.Context, *connect.Request[v1.WaitTaskRequest]) (*connect.Response[v1.WaitTaskResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cap.v1.TaskService.Wait is not implemented"))
}
