// Cloud Agent Platform — TaskService API
//
// This service defines the core task management operations for the Cloud Agent Platform.
// All capabilities are exposed via MCP Tools; REST API is an equivalent HTTP translation layer.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: task.proto

package capv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TaskStatus represents the lifecycle state of a task.
type TaskStatus int32

const (
	TaskStatus_TASK_STATUS_UNSPECIFIED TaskStatus = 0
	TaskStatus_TASK_STATUS_PENDING     TaskStatus = 1 // Queued, not yet started
	TaskStatus_TASK_STATUS_DECOMPOSING TaskStatus = 2 // Task is being decomposed into subtasks
	TaskStatus_TASK_STATUS_DISPATCHED  TaskStatus = 3 // Dispatched to an Agent
	TaskStatus_TASK_STATUS_RUNNING     TaskStatus = 4 // Actively executing
	TaskStatus_TASK_STATUS_REVIEWING   TaskStatus = 5 // Agent output is under review
	TaskStatus_TASK_STATUS_CONFIRMING  TaskStatus = 6 // Waiting for user confirmation
	TaskStatus_TASK_STATUS_COMPLETED   TaskStatus = 7 // Finished successfully
	TaskStatus_TASK_STATUS_FAILED      TaskStatus = 8 // Failed
	TaskStatus_TASK_STATUS_CANCELLED   TaskStatus = 9 // Cancelled by user
)

// Enum value maps for TaskStatus.
var (
	TaskStatus_name = map[int32]string{
		0: "TASK_STATUS_UNSPECIFIED",
		1: "TASK_STATUS_PENDING",
		2: "TASK_STATUS_DECOMPOSING",
		3: "TASK_STATUS_DISPATCHED",
		4: "TASK_STATUS_RUNNING",
		5: "TASK_STATUS_REVIEWING",
		6: "TASK_STATUS_CONFIRMING",
		7: "TASK_STATUS_COMPLETED",
		8: "TASK_STATUS_FAILED",
		9: "TASK_STATUS_CANCELLED",
	}
	TaskStatus_value = map[string]int32{
		"TASK_STATUS_UNSPECIFIED": 0,
		"TASK_STATUS_PENDING":     1,
		"TASK_STATUS_DECOMPOSING": 2,
		"TASK_STATUS_DISPATCHED":  3,
		"TASK_STATUS_RUNNING":     4,
		"TASK_STATUS_REVIEWING":   5,
		"TASK_STATUS_CONFIRMING":  6,
		"TASK_STATUS_COMPLETED":   7,
		"TASK_STATUS_FAILED":      8,
		"TASK_STATUS_CANCELLED":   9,
	}
)

func (x TaskStatus) Enum() *TaskStatus {
	p := new(TaskStatus)
	*p = x
	return p
}

func (x TaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_task_proto_enumTypes[0].Descriptor()
}

func (TaskStatus) Type() protoreflect.EnumType {
	return &file_task_proto_enumTypes[0]
}

func (x TaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskStatus.Descriptor instead.
func (TaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{0}
}

// SubtaskType represents the type/capability of a subtask.
type SubtaskType int32

const (
	SubtaskType_SUBTASK_TYPE_UNSPECIFIED SubtaskType = 0
	SubtaskType_SUBTASK_TYPE_ANALYSIS    SubtaskType = 1
	SubtaskType_SUBTASK_TYPE_CODING      SubtaskType = 2
	SubtaskType_SUBTASK_TYPE_REVIEW      SubtaskType = 3
	SubtaskType_SUBTASK_TYPE_TESTING     SubtaskType = 4
	SubtaskType_SUBTASK_TYPE_RESEARCH    SubtaskType = 5
)

// Enum value maps for SubtaskType.
var (
	SubtaskType_name = map[int32]string{
		0: "SUBTASK_TYPE_UNSPECIFIED",
		1: "SUBTASK_TYPE_ANALYSIS",
		2: "SUBTASK_TYPE_CODING",
		3: "SUBTASK_TYPE_REVIEW",
		4: "SUBTASK_TYPE_TESTING",
		5: "SUBTASK_TYPE_RESEARCH",
	}
	SubtaskType_value = map[string]int32{
		"SUBTASK_TYPE_UNSPECIFIED": 0,
		"SUBTASK_TYPE_ANALYSIS":    1,
		"SUBTASK_TYPE_CODING":      2,
		"SUBTASK_TYPE_REVIEW":      3,
		"SUBTASK_TYPE_TESTING":     4,
		"SUBTASK_TYPE_RESEARCH":    5,
	}
)

func (x SubtaskType) Enum() *SubtaskType {
	p := new(SubtaskType)
	*p = x
	return p
}

func (x SubtaskType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SubtaskType) Descriptor() protoreflect.EnumDescriptor {
	return file_task_proto_enumTypes[1].Descriptor()
}

func (SubtaskType) Type() protoreflect.EnumType {
	return &file_task_proto_enumTypes[1]
}

func (x SubtaskType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SubtaskType.Descriptor instead.
func (SubtaskType) EnumDescriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{1}
}

// ArtifactType represents the type of an artifact.
type ArtifactType int32

const (
	ArtifactType_ARTIFACT_TYPE_UNSPECIFIED ArtifactType = 0
	ArtifactType_ARTIFACT_TYPE_ANALYSIS    ArtifactType = 1
	ArtifactType_ARTIFACT_TYPE_DIFF        ArtifactType = 2
	ArtifactType_ARTIFACT_TYPE_TEST_RESULT ArtifactType = 3
	ArtifactType_ARTIFACT_TYPE_REPORT      ArtifactType = 4
	ArtifactType_ARTIFACT_TYPE_LOG         ArtifactType = 5
)

// Enum value maps for ArtifactType.
var (
	ArtifactType_name = map[int32]string{
		0: "ARTIFACT_TYPE_UNSPECIFIED",
		1: "ARTIFACT_TYPE_ANALYSIS",
		2: "ARTIFACT_TYPE_DIFF",
		3: "ARTIFACT_TYPE_TEST_RESULT",
		4: "ARTIFACT_TYPE_REPORT",
		5: "ARTIFACT_TYPE_LOG",
	}
	ArtifactType_value = map[string]int32{
		"ARTIFACT_TYPE_UNSPECIFIED": 0,
		"ARTIFACT_TYPE_ANALYSIS":    1,
		"ARTIFACT_TYPE_DIFF":        2,
		"ARTIFACT_TYPE_TEST_RESULT": 3,
		"ARTIFACT_TYPE_REPORT":      4,
		"ARTIFACT_TYPE_LOG":         5,
	}
)

func (x ArtifactType) Enum() *ArtifactType {
	p := new(ArtifactType)
	*p = x
	return p
}

func (x ArtifactType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ArtifactType) Descriptor() protoreflect.EnumDescriptor {
	return file_task_proto_enumTypes[2].Descriptor()
}

func (ArtifactType) Type() protoreflect.EnumType {
	return &file_task_proto_enumTypes[2]
}

func (x ArtifactType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ArtifactType.Descriptor instead.
func (ArtifactType) EnumDescriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{2}
}

// UserDecision represents a user's decision on a confirmation request.
type UserDecision int32

const (
	UserDecision_USER_DECISION_UNSPECIFIED UserDecision = 0
	UserDecision_USER_DECISION_APPROVE     UserDecision = 1
	UserDecision_USER_DECISION_REJECT      UserDecision = 2
	UserDecision_USER_DECISION_MODIFY      UserDecision = 3
)

// Enum value maps for UserDecision.
var (
	UserDecision_name = map[int32]string{
		0: "USER_DECISION_UNSPECIFIED",
		1: "USER_DECISION_APPROVE",
		2: "USER_DECISION_REJECT",
		3: "USER_DECISION_MODIFY",
	}
	UserDecision_value = map[string]int32{
		"USER_DECISION_UNSPECIFIED": 0,
		"USER_DECISION_APPROVE":     1,
		"USER_DECISION_REJECT":      2,
		"USER_DECISION_MODIFY":      3,
	}
)

func (x UserDecision) Enum() *UserDecision {
	p := new(UserDecision)
	*p = x
	return p
}

func (x UserDecision) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserDecision) Descriptor() protoreflect.EnumDescriptor {
	return file_task_proto_enumTypes[3].Descriptor()
}

func (UserDecision) Type() protoreflect.EnumType {
	return &file_task_proto_enumTypes[3]
}

func (x UserDecision) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserDecision.Descriptor instead.
func (UserDecision) EnumDescriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{3}
}

type CredentialsType int32

const (
	CredentialsType_CREDENTIALS_TYPE_UNSPECIFIED CredentialsType = 0
	CredentialsType_CREDENTIALS_TYPE_SSH_KEY     CredentialsType = 1
	CredentialsType_CREDENTIALS_TYPE_TOKEN       CredentialsType = 2
)

// Enum value maps for CredentialsType.
var (
	CredentialsType_name = map[int32]string{
		0: "CREDENTIALS_TYPE_UNSPECIFIED",
		1: "CREDENTIALS_TYPE_SSH_KEY",
		2: "CREDENTIALS_TYPE_TOKEN",
	}
	CredentialsType_value = map[string]int32{
		"CREDENTIALS_TYPE_UNSPECIFIED": 0,
		"CREDENTIALS_TYPE_SSH_KEY":     1,
		"CREDENTIALS_TYPE_TOKEN":       2,
	}
)

func (x CredentialsType) Enum() *CredentialsType {
	p := new(CredentialsType)
	*p = x
	return p
}

func (x CredentialsType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CredentialsType) Descriptor() protoreflect.EnumDescriptor {
	return file_task_proto_enumTypes[4].Descriptor()
}

func (CredentialsType) Type() protoreflect.EnumType {
	return &file_task_proto_enumTypes[4]
}

func (x CredentialsType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CredentialsType.Descriptor instead.
func (CredentialsType) EnumDescriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{4}
}

type FileChangeAction int32

const (
	FileChangeAction_FILE_CHANGE_ACTION_UNSPECIFIED FileChangeAction = 0
	FileChangeAction_FILE_CHANGE_ACTION_ADDED       FileChangeAction = 1
	FileChangeAction_FILE_CHANGE_ACTION_MODIFIED    FileChangeAction = 2
	FileChangeAction_FILE_CHANGE_ACTION_DELETED     FileChangeAction = 3
)

// Enum value maps for FileChangeAction.
var (
	FileChangeAction_name = map[int32]string{
		0: "FILE_CHANGE_ACTION_UNSPECIFIED",
		1: "FILE_CHANGE_ACTION_ADDED",
		2: "FILE_CHANGE_ACTION_MODIFIED",
		3: "FILE_CHANGE_ACTION_DELETED",
	}
	FileChangeAction_value = map[string]int32{
		"FILE_CHANGE_ACTION_UNSPECIFIED": 0,
		"FILE_CHANGE_ACTION_ADDED":       1,
		"FILE_CHANGE_ACTION_MODIFIED":    2,
		"FILE_CHANGE_ACTION_DELETED":     3,
	}
)

func (x FileChangeAction) Enum() *FileChangeAction {
	p := new(FileChangeAction)
	*p = x
	return p
}

func (x FileChangeAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileChangeAction) Descriptor() protoreflect.EnumDescriptor {
	return file_task_proto_enumTypes[5].Descriptor()
}

func (FileChangeAction) Type() protoreflect.EnumType {
	return &file_task_proto_enumTypes[5]
}

func (x FileChangeAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileChangeAction.Descriptor instead.
func (FileChangeAction) EnumDescriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{5}
}

// Repository describes a Git repository for task context.
type Repository struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`                                       // Git repository HTTPS address
	Branch        string                 `protobuf:"bytes,2,opt,name=branch,proto3" json:"branch,omitempty"`                                 // Base branch
	ResultBranch  string                 `protobuf:"bytes,3,opt,name=result_branch,json=resultBranch,proto3" json:"result_branch,omitempty"` // Result branch (default: auto-generated)
	Credentials   *Credentials           `protobuf:"bytes,4,opt,name=credentials,proto3" json:"credentials,omitempty"`                       // Optional Git credentials
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Repository) Reset() {
	*x = Repository{}
	mi := &file_task_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Repository) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Repository) ProtoMessage() {}

func (x *Repository) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Repository.ProtoReflect.Descriptor instead.
func (*Repository) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{0}
}

func (x *Repository) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Repository) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *Repository) GetResultBranch() string {
	if x != nil {
		return x.ResultBranch
	}
	return ""
}

func (x *Repository) GetCredentials() *Credentials {
	if x != nil {
		return x.Credentials
	}
	return nil
}

type Credentials struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          CredentialsType        `protobuf:"varint,1,opt,name=type,proto3,enum=cap.v1.CredentialsType" json:"type,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"` // Encrypted value
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Credentials) Reset() {
	*x = Credentials{}
	mi := &file_task_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Credentials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Credentials) ProtoMessage() {}

func (x *Credentials) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Credentials.ProtoReflect.Descriptor instead.
func (*Credentials) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{1}
}

func (x *Credentials) GetType() CredentialsType {
	if x != nil {
		return x.Type
	}
	return CredentialsType_CREDENTIALS_TYPE_UNSPECIFIED
}

func (x *Credentials) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// AgentHint suggests Agent configuration for a task.
type AgentHint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Templates     []string               `protobuf:"bytes,1,rep,name=templates,proto3" json:"templates,omitempty"`                   // Suggested Agent template IDs
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`                           // Suggested model
	MaxAgents     int32                  `protobuf:"varint,3,opt,name=max_agents,json=maxAgents,proto3" json:"max_agents,omitempty"` // Max concurrent Agents
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentHint) Reset() {
	*x = AgentHint{}
	mi := &file_task_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentHint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentHint) ProtoMessage() {}

func (x *AgentHint) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentHint.ProtoReflect.Descriptor instead.
func (*AgentHint) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{2}
}

func (x *AgentHint) GetTemplates() []string {
	if x != nil {
		return x.Templates
	}
	return nil
}

func (x *AgentHint) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *AgentHint) GetMaxAgents() int32 {
	if x != nil {
		return x.MaxAgents
	}
	return 0
}

// SubmitTaskRequest is the request for the Submit RPC.
type SubmitTaskRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required
	Goal string `protobuf:"bytes,1,opt,name=goal,proto3" json:"goal,omitempty"` // Task goal (one sentence)
	// Code context
	Repository *Repository `protobuf:"bytes,2,opt,name=repository,proto3" json:"repository,omitempty"`
	// Constraints
	Constraints          []string `protobuf:"bytes,3,rep,name=constraints,proto3" json:"constraints,omitempty"`                                               // Constraint conditions
	VerificationCriteria []string `protobuf:"bytes,4,rep,name=verification_criteria,json=verificationCriteria,proto3" json:"verification_criteria,omitempty"` // Acceptance criteria
	// Optional
	Priority      int32      `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"` // 0-9, default 5
	Timeout       int32      `protobuf:"varint,6,opt,name=timeout,proto3" json:"timeout,omitempty"`   // Seconds, default 1800 (30min)
	AgentHint     *AgentHint `protobuf:"bytes,7,opt,name=agent_hint,json=agentHint,proto3" json:"agent_hint,omitempty"`
	LocalContext  string     `protobuf:"bytes,8,opt,name=local_context,json=localContext,proto3" json:"local_context,omitempty"` // Client-supplied context
	Tags          []string   `protobuf:"bytes,9,rep,name=tags,proto3" json:"tags,omitempty"`                                     // Task tags
	CallbackUrl   string     `protobuf:"bytes,10,opt,name=callback_url,json=callbackUrl,proto3" json:"callback_url,omitempty"`   // Completion callback URL
	IdemKey       string     `protobuf:"bytes,11,opt,name=idem_key,json=idemKey,proto3" json:"idem_key,omitempty"`               // Idempotency key (X-Request-ID)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitTaskRequest) Reset() {
	*x = SubmitTaskRequest{}
	mi := &file_task_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTaskRequest) ProtoMessage() {}

func (x *SubmitTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTaskRequest.ProtoReflect.Descriptor instead.
func (*SubmitTaskRequest) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{3}
}

func (x *SubmitTaskRequest) GetGoal() string {
	if x != nil {
		return x.Goal
	}
	return ""
}

func (x *SubmitTaskRequest) GetRepository() *Repository {
	if x != nil {
		return x.Repository
	}
	return nil
}

func (x *SubmitTaskRequest) GetConstraints() []string {
	if x != nil {
		return x.Constraints
	}
	return nil
}

func (x *SubmitTaskRequest) GetVerificationCriteria() []string {
	if x != nil {
		return x.VerificationCriteria
	}
	return nil
}

func (x *SubmitTaskRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *SubmitTaskRequest) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *SubmitTaskRequest) GetAgentHint() *AgentHint {
	if x != nil {
		return x.AgentHint
	}
	return nil
}

func (x *SubmitTaskRequest) GetLocalContext() string {
	if x != nil {
		return x.LocalContext
	}
	return ""
}

func (x *SubmitTaskRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *SubmitTaskRequest) GetCallbackUrl() string {
	if x != nil {
		return x.CallbackUrl
	}
	return ""
}

func (x *SubmitTaskRequest) GetIdemKey() string {
	if x != nil {
		return x.IdemKey
	}
	return ""
}

// SubmitTaskResponse is the response for the Submit RPC.
type SubmitTaskResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TaskId            string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status            TaskStatus             `protobuf:"varint,2,opt,name=status,proto3,enum=cap.v1.TaskStatus" json:"status,omitempty"`
	ResultBranch      string                 `protobuf:"bytes,3,opt,name=result_branch,json=resultBranch,proto3" json:"result_branch,omitempty"`
	CreatedAt         string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                          // ISO 8601
	EstimatedDuration int32                  `protobuf:"varint,5,opt,name=estimated_duration,json=estimatedDuration,proto3" json:"estimated_duration,omitempty"` // Estimated completion time in seconds
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SubmitTaskResponse) Reset() {
	*x = SubmitTaskResponse{}
	mi := &file_task_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTaskResponse) ProtoMessage() {}

func (x *SubmitTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTaskResponse.ProtoReflect.Descriptor instead.
func (*SubmitTaskResponse) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{4}
}

func (x *SubmitTaskResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *SubmitTaskResponse) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

func (x *SubmitTaskResponse) GetResultBranch() string {
	if x != nil {
		return x.ResultBranch
	}
	return ""
}

func (x *SubmitTaskResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *SubmitTaskResponse) GetEstimatedDuration() int32 {
	if x != nil {
		return x.EstimatedDuration
	}
	return 0
}

// GetTaskRequest is the request for the Get RPC.
type GetTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	IncludeLog    bool                   `protobuf:"varint,2,opt,name=include_log,json=includeLog,proto3" json:"include_log,omitempty"`    // Include latest 20 Agent log entries
	IncludeDiff   bool                   `protobuf:"varint,3,opt,name=include_diff,json=includeDiff,proto3" json:"include_diff,omitempty"` // Include diff summary (completed tasks only)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_task_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{5}
}

func (x *GetTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *GetTaskRequest) GetIncludeLog() bool {
	if x != nil {
		return x.IncludeLog
	}
	return false
}

func (x *GetTaskRequest) GetIncludeDiff() bool {
	if x != nil {
		return x.IncludeDiff
	}
	return false
}

// GetTaskResponse is the response for the Get RPC.
type GetTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskResponse) Reset() {
	*x = GetTaskResponse{}
	mi := &file_task_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskResponse) ProtoMessage() {}

func (x *GetTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskResponse.ProtoReflect.Descriptor instead.
func (*GetTaskResponse) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{6}
}

func (x *GetTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

// Task represents the full task state.
type Task struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	TaskId       string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status       TaskStatus             `protobuf:"varint,2,opt,name=status,proto3,enum=cap.v1.TaskStatus" json:"status,omitempty"`
	Goal         string                 `protobuf:"bytes,3,opt,name=goal,proto3" json:"goal,omitempty"`
	Priority     int32                  `protobuf:"varint,4,opt,name=priority,proto3" json:"priority,omitempty"`
	ResultBranch string                 `protobuf:"bytes,5,opt,name=result_branch,json=resultBranch,proto3" json:"result_branch,omitempty"`
	// Progress
	Progress     int32  `protobuf:"varint,6,opt,name=progress,proto3" json:"progress,omitempty"`                            // 0-100
	CurrentPhase string `protobuf:"bytes,7,opt,name=current_phase,json=currentPhase,proto3" json:"current_phase,omitempty"` // Current phase description
	// Subtasks
	Subtasks []*Subtask `protobuf:"bytes,8,rep,name=subtasks,proto3" json:"subtasks,omitempty"`
	// Timing
	CreatedAt   string `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`        // ISO 8601
	StartedAt   string `protobuf:"bytes,10,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`       // ISO 8601
	CompletedAt string `protobuf:"bytes,11,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"` // ISO 8601
	// Result (available after completion)
	Result *TaskResult `protobuf:"bytes,12,opt,name=result,proto3" json:"result,omitempty"`
	// Stats
	Stats         *TaskStats `protobuf:"bytes,13,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_task_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{7}
}

func (x *Task) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *Task) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

func (x *Task) GetGoal() string {
	if x != nil {
		return x.Goal
	}
	return ""
}

func (x *Task) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Task) GetResultBranch() string {
	if x != nil {
		return x.ResultBranch
	}
	return ""
}

func (x *Task) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *Task) GetCurrentPhase() string {
	if x != nil {
		return x.CurrentPhase
	}
	return ""
}

func (x *Task) GetSubtasks() []*Subtask {
	if x != nil {
		return x.Subtasks
	}
	return nil
}

func (x *Task) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Task) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *Task) GetCompletedAt() string {
	if x != nil {
		return x.CompletedAt
	}
	return ""
}

func (x *Task) GetResult() *TaskResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *Task) GetStats() *TaskStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

// Subtask represents a sub-task within a parent task.
type Subtask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubtaskId     string                 `protobuf:"bytes,1,opt,name=subtask_id,json=subtaskId,proto3" json:"subtask_id,omitempty"`
	Type          SubtaskType            `protobuf:"varint,2,opt,name=type,proto3,enum=cap.v1.SubtaskType" json:"type,omitempty"`
	AgentTemplate string                 `protobuf:"bytes,3,opt,name=agent_template,json=agentTemplate,proto3" json:"agent_template,omitempty"`
	Status        TaskStatus             `protobuf:"varint,4,opt,name=status,proto3,enum=cap.v1.TaskStatus" json:"status,omitempty"`
	Summary       string                 `protobuf:"bytes,5,opt,name=summary,proto3" json:"summary,omitempty"` // Agent output summary
	Artifacts     []*Artifact            `protobuf:"bytes,6,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
	StartedAt     string                 `protobuf:"bytes,7,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`       // ISO 8601
	CompletedAt   string                 `protobuf:"bytes,8,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"` // ISO 8601
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subtask) Reset() {
	*x = Subtask{}
	mi := &file_task_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subtask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subtask) ProtoMessage() {}

func (x *Subtask) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subtask.ProtoReflect.Descriptor instead.
func (*Subtask) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{8}
}

func (x *Subtask) GetSubtaskId() string {
	if x != nil {
		return x.SubtaskId
	}
	return ""
}

func (x *Subtask) GetType() SubtaskType {
	if x != nil {
		return x.Type
	}
	return SubtaskType_SUBTASK_TYPE_UNSPECIFIED
}

func (x *Subtask) GetAgentTemplate() string {
	if x != nil {
		return x.AgentTemplate
	}
	return ""
}

func (x *Subtask) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

func (x *Subtask) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *Subtask) GetArtifacts() []*Artifact {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

func (x *Subtask) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *Subtask) GetCompletedAt() string {
	if x != nil {
		return x.CompletedAt
	}
	return ""
}

// Artifact represents a produced artifact from a subtask.
type Artifact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArtifactId    string                 `protobuf:"bytes,1,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	Type          ArtifactType           `protobuf:"varint,2,opt,name=type,proto3,enum=cap.v1.ArtifactType" json:"type,omitempty"`
	Summary       string                 `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	Url           string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`    // Download URL (signed, 1h validity)
	Size          int64                  `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"` // Bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Artifact) Reset() {
	*x = Artifact{}
	mi := &file_task_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Artifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Artifact) ProtoMessage() {}

func (x *Artifact) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Artifact.ProtoReflect.Descriptor instead.
func (*Artifact) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{9}
}

func (x *Artifact) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

func (x *Artifact) GetType() ArtifactType {
	if x != nil {
		return x.Type
	}
	return ArtifactType_ARTIFACT_TYPE_UNSPECIFIED
}

func (x *Artifact) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *Artifact) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Artifact) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

// TaskResult represents the final result of a completed task.
type TaskResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GitCommit     string                 `protobuf:"bytes,1,opt,name=git_commit,json=gitCommit,proto3" json:"git_commit,omitempty"`
	GitBranch     string                 `protobuf:"bytes,2,opt,name=git_branch,json=gitBranch,proto3" json:"git_branch,omitempty"`
	Summary       string                 `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"` // Task summary
	Changes       []*FileChange          `protobuf:"bytes,4,rep,name=changes,proto3" json:"changes,omitempty"`
	TestResult    *TestResult            `protobuf:"bytes,5,opt,name=test_result,json=testResult,proto3" json:"test_result,omitempty"`
	QualityScore  int32                  `protobuf:"varint,6,opt,name=quality_score,json=qualityScore,proto3" json:"quality_score,omitempty"` // 0-100
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResult) Reset() {
	*x = TaskResult{}
	mi := &file_task_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResult) ProtoMessage() {}

func (x *TaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResult.ProtoReflect.Descriptor instead.
func (*TaskResult) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{10}
}

func (x *TaskResult) GetGitCommit() string {
	if x != nil {
		return x.GitCommit
	}
	return ""
}

func (x *TaskResult) GetGitBranch() string {
	if x != nil {
		return x.GitBranch
	}
	return ""
}

func (x *TaskResult) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *TaskResult) GetChanges() []*FileChange {
	if x != nil {
		return x.Changes
	}
	return nil
}

func (x *TaskResult) GetTestResult() *TestResult {
	if x != nil {
		return x.TestResult
	}
	return nil
}

func (x *TaskResult) GetQualityScore() int32 {
	if x != nil {
		return x.QualityScore
	}
	return 0
}

// FileChange represents a single file change in the result.
type FileChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Action        FileChangeAction       `protobuf:"varint,2,opt,name=action,proto3,enum=cap.v1.FileChangeAction" json:"action,omitempty"`
	Additions     int32                  `protobuf:"varint,3,opt,name=additions,proto3" json:"additions,omitempty"`
	Deletions     int32                  `protobuf:"varint,4,opt,name=deletions,proto3" json:"deletions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileChange) Reset() {
	*x = FileChange{}
	mi := &file_task_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChange) ProtoMessage() {}

func (x *FileChange) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChange.ProtoReflect.Descriptor instead.
func (*FileChange) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{11}
}

func (x *FileChange) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileChange) GetAction() FileChangeAction {
	if x != nil {
		return x.Action
	}
	return FileChangeAction_FILE_CHANGE_ACTION_UNSPECIFIED
}

func (x *FileChange) GetAdditions() int32 {
	if x != nil {
		return x.Additions
	}
	return 0
}

func (x *FileChange) GetDeletions() int32 {
	if x != nil {
		return x.Deletions
	}
	return 0
}

// TestResult represents test execution results.
type TestResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Passed        int32                  `protobuf:"varint,2,opt,name=passed,proto3" json:"passed,omitempty"`
	Failed        int32                  `protobuf:"varint,3,opt,name=failed,proto3" json:"failed,omitempty"`
	Coverage      int32                  `protobuf:"varint,4,opt,name=coverage,proto3" json:"coverage,omitempty"` // 0-100
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestResult) Reset() {
	*x = TestResult{}
	mi := &file_task_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestResult) ProtoMessage() {}

func (x *TestResult) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestResult.ProtoReflect.Descriptor instead.
func (*TestResult) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{12}
}

func (x *TestResult) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *TestResult) GetPassed() int32 {
	if x != nil {
		return x.Passed
	}
	return 0
}

func (x *TestResult) GetFailed() int32 {
	if x != nil {
		return x.Failed
	}
	return 0
}

func (x *TestResult) GetCoverage() int32 {
	if x != nil {
		return x.Coverage
	}
	return 0
}

// TaskStats represents task execution statistics.
type TaskStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentsUsed    int32                  `protobuf:"varint,1,opt,name=agents_used,json=agentsUsed,proto3" json:"agents_used,omitempty"`
	TokensUsed    int64                  `protobuf:"varint,2,opt,name=tokens_used,json=tokensUsed,proto3" json:"tokens_used,omitempty"`
	EstimatedCost float64                `protobuf:"fixed64,3,opt,name=estimated_cost,json=estimatedCost,proto3" json:"estimated_cost,omitempty"` // CNY
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskStats) Reset() {
	*x = TaskStats{}
	mi := &file_task_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskStats) ProtoMessage() {}

func (x *TaskStats) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskStats.ProtoReflect.Descriptor instead.
func (*TaskStats) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{13}
}

func (x *TaskStats) GetAgentsUsed() int32 {
	if x != nil {
		return x.AgentsUsed
	}
	return 0
}

func (x *TaskStats) GetTokensUsed() int64 {
	if x != nil {
		return x.TokensUsed
	}
	return 0
}

func (x *TaskStats) GetEstimatedCost() float64 {
	if x != nil {
		return x.EstimatedCost
	}
	return 0
}

// ListTasksRequest is the request for the List RPC.
type ListTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        TaskStatus             `protobuf:"varint,1,opt,name=status,proto3,enum=cap.v1.TaskStatus" json:"status,omitempty"` // Filter by status
	Tags          []string               `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`                             // Filter by tags
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`                            // Page number (default 1)
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`    // Page size (default 20, max 100)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksRequest) Reset() {
	*x = ListTasksRequest{}
	mi := &file_task_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksRequest) ProtoMessage() {}

func (x *ListTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksRequest.ProtoReflect.Descriptor instead.
func (*ListTasksRequest) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{14}
}

func (x *ListTasksRequest) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

func (x *ListTasksRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ListTasksRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListTasksRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// ListTasksResponse is the response for the List RPC.
type ListTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*Task                `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksResponse) Reset() {
	*x = ListTasksResponse{}
	mi := &file_task_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksResponse) ProtoMessage() {}

func (x *ListTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksResponse.ProtoReflect.Descriptor instead.
func (*ListTasksResponse) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{15}
}

func (x *ListTasksResponse) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *ListTasksResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListTasksResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListTasksResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// CancelTaskRequest is the request for the Cancel RPC.
type CancelTaskRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TaskId          string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Reason          string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	TerminateAgents bool                   `protobuf:"varint,3,opt,name=terminate_agents,json=terminateAgents,proto3" json:"terminate_agents,omitempty"` // Terminate running Agents (default true)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CancelTaskRequest) Reset() {
	*x = CancelTaskRequest{}
	mi := &file_task_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskRequest) ProtoMessage() {}

func (x *CancelTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskRequest.ProtoReflect.Descriptor instead.
func (*CancelTaskRequest) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{16}
}

func (x *CancelTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *CancelTaskRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *CancelTaskRequest) GetTerminateAgents() bool {
	if x != nil {
		return x.TerminateAgents
	}
	return false
}

// CancelTaskResponse is the response for the Cancel RPC.
type CancelTaskResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TaskId           string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status           TaskStatus             `protobuf:"varint,2,opt,name=status,proto3,enum=cap.v1.TaskStatus" json:"status,omitempty"`
	TerminatedAgents []string               `protobuf:"bytes,3,rep,name=terminated_agents,json=terminatedAgents,proto3" json:"terminated_agents,omitempty"`
	PartialResult    *Artifact              `protobuf:"bytes,4,opt,name=partial_result,json=partialResult,proto3" json:"partial_result,omitempty"` // Partial output if any
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CancelTaskResponse) Reset() {
	*x = CancelTaskResponse{}
	mi := &file_task_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskResponse) ProtoMessage() {}

func (x *CancelTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskResponse.ProtoReflect.Descriptor instead.
func (*CancelTaskResponse) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{17}
}

func (x *CancelTaskResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *CancelTaskResponse) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

func (x *CancelTaskResponse) GetTerminatedAgents() []string {
	if x != nil {
		return x.TerminatedAgents
	}
	return nil
}

func (x *CancelTaskResponse) GetPartialResult() *Artifact {
	if x != nil {
		return x.PartialResult
	}
	return nil
}

// DecideRequest is the request for the Decide RPC.
type DecideRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	SubtaskId     string                 `protobuf:"bytes,2,opt,name=subtask_id,json=subtaskId,proto3" json:"subtask_id,omitempty"`
	Decision      UserDecision           `protobuf:"varint,3,opt,name=decision,proto3,enum=cap.v1.UserDecision" json:"decision,omitempty"`
	Feedback      string                 `protobuf:"bytes,4,opt,name=feedback,proto3" json:"feedback,omitempty"`           // Required when decision is reject or modify
	Modifications string                 `protobuf:"bytes,5,opt,name=modifications,proto3" json:"modifications,omitempty"` // Modification suggestions (when decision=modify)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecideRequest) Reset() {
	*x = DecideRequest{}
	mi := &file_task_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecideRequest) ProtoMessage() {}

func (x *DecideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecideRequest.ProtoReflect.Descriptor instead.
func (*DecideRequest) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{18}
}

func (x *DecideRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *DecideRequest) GetSubtaskId() string {
	if x != nil {
		return x.SubtaskId
	}
	return ""
}

func (x *DecideRequest) GetDecision() UserDecision {
	if x != nil {
		return x.Decision
	}
	return UserDecision_USER_DECISION_UNSPECIFIED
}

func (x *DecideRequest) GetFeedback() string {
	if x != nil {
		return x.Feedback
	}
	return ""
}

func (x *DecideRequest) GetModifications() string {
	if x != nil {
		return x.Modifications
	}
	return ""
}

// DecideResponse is the response for the Decide RPC.
type DecideResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	SubtaskId     string                 `protobuf:"bytes,2,opt,name=subtask_id,json=subtaskId,proto3" json:"subtask_id,omitempty"`
	Status        TaskStatus             `protobuf:"varint,3,opt,name=status,proto3,enum=cap.v1.TaskStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecideResponse) Reset() {
	*x = DecideResponse{}
	mi := &file_task_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecideResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecideResponse) ProtoMessage() {}

func (x *DecideResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecideResponse.ProtoReflect.Descriptor instead.
func (*DecideResponse) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{19}
}

func (x *DecideResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *DecideResponse) GetSubtaskId() string {
	if x != nil {
		return x.SubtaskId
	}
	return ""
}

func (x *DecideResponse) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

// GetArtifactRequest is the request for the GetArtifact RPC.
type GetArtifactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ArtifactId    string                 `protobuf:"bytes,2,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArtifactRequest) Reset() {
	*x = GetArtifactRequest{}
	mi := &file_task_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArtifactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArtifactRequest) ProtoMessage() {}

func (x *GetArtifactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArtifactRequest.ProtoReflect.Descriptor instead.
func (*GetArtifactRequest) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{20}
}

func (x *GetArtifactRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *GetArtifactRequest) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

// GetArtifactResponse is the response for the GetArtifact RPC.
type GetArtifactResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Artifact      *Artifact              `protobuf:"bytes,1,opt,name=artifact,proto3" json:"artifact,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`                            // File content bytes
	ContentType   string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"` // MIME type
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArtifactResponse) Reset() {
	*x = GetArtifactResponse{}
	mi := &file_task_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArtifactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArtifactResponse) ProtoMessage() {}

func (x *GetArtifactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArtifactResponse.ProtoReflect.Descriptor instead.
func (*GetArtifactResponse) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{21}
}

func (x *GetArtifactResponse) GetArtifact() *Artifact {
	if x != nil {
		return x.Artifact
	}
	return nil
}

func (x *GetArtifactResponse) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *GetArtifactResponse) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

// GetDiffRequest is the request for the GetDiff RPC.
type GetDiffRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	MaxLines      int32                  `protobuf:"varint,2,opt,name=max_lines,json=maxLines,proto3" json:"max_lines,omitempty"` // Max diff lines (default 500)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDiffRequest) Reset() {
	*x = GetDiffRequest{}
	mi := &file_task_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDiffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDiffRequest) ProtoMessage() {}

func (x *GetDiffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDiffRequest.ProtoReflect.Descriptor instead.
func (*GetDiffRequest) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{22}
}

func (x *GetDiffRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *GetDiffRequest) GetMaxLines() int32 {
	if x != nil {
		return x.MaxLines
	}
	return 0
}

// GetDiffResponse is the response for the GetDiff RPC.
type GetDiffResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Diff          string                 `protobuf:"bytes,1,opt,name=diff,proto3" json:"diff,omitempty"` // Unified diff format
	Stats         *DiffStats             `protobuf:"bytes,2,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDiffResponse) Reset() {
	*x = GetDiffResponse{}
	mi := &file_task_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDiffResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDiffResponse) ProtoMessage() {}

func (x *GetDiffResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDiffResponse.ProtoReflect.Descriptor instead.
func (*GetDiffResponse) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{23}
}

func (x *GetDiffResponse) GetDiff() string {
	if x != nil {
		return x.Diff
	}
	return ""
}

func (x *GetDiffResponse) GetStats() *DiffStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

// DiffStats summarizes diff statistics.
type DiffStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         int32                  `protobuf:"varint,1,opt,name=files,proto3" json:"files,omitempty"`
	Additions     int32                  `protobuf:"varint,2,opt,name=additions,proto3" json:"additions,omitempty"`
	Deletions     int32                  `protobuf:"varint,3,opt,name=deletions,proto3" json:"deletions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiffStats) Reset() {
	*x = DiffStats{}
	mi := &file_task_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiffStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiffStats) ProtoMessage() {}

func (x *DiffStats) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiffStats.ProtoReflect.Descriptor instead.
func (*DiffStats) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{24}
}

func (x *DiffStats) GetFiles() int32 {
	if x != nil {
		return x.Files
	}
	return 0
}

func (x *DiffStats) GetAdditions() int32 {
	if x != nil {
		return x.Additions
	}
	return 0
}

func (x *DiffStats) GetDeletions() int32 {
	if x != nil {
		return x.Deletions
	}
	return 0
}

// WaitTaskRequest is the request for the Wait RPC.
type WaitTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Timeout       int32                  `protobuf:"varint,2,opt,name=timeout,proto3" json:"timeout,omitempty"`                               // Wait timeout in seconds (default 600)
	PollInterval  int32                  `protobuf:"varint,3,opt,name=poll_interval,json=pollInterval,proto3" json:"poll_interval,omitempty"` // Poll interval in seconds (default 5)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitTaskRequest) Reset() {
	*x = WaitTaskRequest{}
	mi := &file_task_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitTaskRequest) ProtoMessage() {}

func (x *WaitTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitTaskRequest.ProtoReflect.Descriptor instead.
func (*WaitTaskRequest) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{25}
}

func (x *WaitTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *WaitTaskRequest) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *WaitTaskRequest) GetPollInterval() int32 {
	if x != nil {
		return x.PollInterval
	}
	return 0
}

// WaitTaskResponse is the response for the Wait RPC.
type WaitTaskResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Task                 *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	TimedOut             bool                   `protobuf:"varint,2,opt,name=timed_out,json=timedOut,proto3" json:"timed_out,omitempty"`
	ConfirmationRequired bool                   `protobuf:"varint,3,opt,name=confirmation_required,json=confirmationRequired,proto3" json:"confirmation_required,omitempty"` // True if task needs user confirmation
	ConfirmSubtaskId     string                 `protobuf:"bytes,4,opt,name=confirm_subtask_id,json=confirmSubtaskId,proto3" json:"confirm_subtask_id,omitempty"`            // Subtask needing confirmation
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *WaitTaskResponse) Reset() {
	*x = WaitTaskResponse{}
	mi := &file_task_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitTaskResponse) ProtoMessage() {}

func (x *WaitTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitTaskResponse.ProtoReflect.Descriptor instead.
func (*WaitTaskResponse) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{26}
}

func (x *WaitTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

func (x *WaitTaskResponse) GetTimedOut() bool {
	if x != nil {
		return x.TimedOut
	}
	return false
}

func (x *WaitTaskResponse) GetConfirmationRequired() bool {
	if x != nil {
		return x.ConfirmationRequired
	}
	return false
}

func (x *WaitTaskResponse) GetConfirmSubtaskId() string {
	if x != nil {
		return x.ConfirmSubtaskId
	}
	return ""
}

var File_task_proto protoreflect.FileDescriptor

const file_task_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"task.proto\x12\x06cap.v1\"\x92\x01\n" +
	"\n" +
	"Repository\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x16\n" +
	"\x06branch\x18\x02 \x01(\tR\x06branch\x12#\n" +
	"\rresult_branch\x18\x03 \x01(\tR\fresultBranch\x125\n" +
	"\vcredentials\x18\x04 \x01(\v2\x13.cap.v1.CredentialsR\vcredentials\"P\n" +
	"\vCredentials\x12+\n" +
	"\x04type\x18\x01 \x01(\x0e2\x17.cap.v1.CredentialsTypeR\x04type\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"^\n" +
	"\tAgentHint\x12\x1c\n" +
	"\ttemplates\x18\x01 \x03(\tR\ttemplates\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x1d\n" +
	"\n" +
	"max_agents\x18\x03 \x01(\x05R\tmaxAgents\"\x91\x03\n" +
	"\x11SubmitTaskRequest\x12\x12\n" +
	"\x04goal\x18\x01 \x01(\tR\x04goal\x122\n" +
	"\n" +
	"repository\x18\x02 \x01(\v2\x12.cap.v1.RepositoryR\n" +
	"repository\x12 \n" +
	"\vconstraints\x18\x03 \x03(\tR\vconstraints\x123\n" +
	"\x15verification_criteria\x18\x04 \x03(\tR\x14verificationCriteria\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\x05R\bpriority\x12\x18\n" +
	"\atimeout\x18\x06 \x01(\x05R\atimeout\x120\n" +
	"\n" +
	"agent_hint\x18\a \x01(\v2\x11.cap.v1.AgentHintR\tagentHint\x12#\n" +
	"\rlocal_context\x18\b \x01(\tR\flocalContext\x12\x12\n" +
	"\x04tags\x18\t \x03(\tR\x04tags\x12!\n" +
	"\fcallback_url\x18\n" +
	" \x01(\tR\vcallbackUrl\x12\x19\n" +
	"\bidem_key\x18\v \x01(\tR\aidemKey\"\xcc\x01\n" +
	"\x12SubmitTaskResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12*\n" +
	"\x06status\x18\x02 \x01(\x0e2\x12.cap.v1.TaskStatusR\x06status\x12#\n" +
	"\rresult_branch\x18\x03 \x01(\tR\fresultBranch\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\x12-\n" +
	"\x12estimated_duration\x18\x05 \x01(\x05R\x11estimatedDuration\"m\n" +
	"\x0eGetTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1f\n" +
	"\vinclude_log\x18\x02 \x01(\bR\n" +
	"includeLog\x12!\n" +
	"\finclude_diff\x18\x03 \x01(\bR\vincludeDiff\"3\n" +
	"\x0fGetTaskResponse\x12 \n" +
	"\x04task\x18\x01 \x01(\v2\f.cap.v1.TaskR\x04task\"\xc4\x03\n" +
	"\x04Task\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12*\n" +
	"\x06status\x18\x02 \x01(\x0e2\x12.cap.v1.TaskStatusR\x06status\x12\x12\n" +
	"\x04goal\x18\x03 \x01(\tR\x04goal\x12\x1a\n" +
	"\bpriority\x18\x04 \x01(\x05R\bpriority\x12#\n" +
	"\rresult_branch\x18\x05 \x01(\tR\fresultBranch\x12\x1a\n" +
	"\bprogress\x18\x06 \x01(\x05R\bprogress\x12#\n" +
	"\rcurrent_phase\x18\a \x01(\tR\fcurrentPhase\x12+\n" +
	"\bsubtasks\x18\b \x03(\v2\x0f.cap.v1.SubtaskR\bsubtasks\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"started_at\x18\n" +
	" \x01(\tR\tstartedAt\x12!\n" +
	"\fcompleted_at\x18\v \x01(\tR\vcompletedAt\x12*\n" +
	"\x06result\x18\f \x01(\v2\x12.cap.v1.TaskResultR\x06result\x12'\n" +
	"\x05stats\x18\r \x01(\v2\x11.cap.v1.TaskStatsR\x05stats\"\xb0\x02\n" +
	"\aSubtask\x12\x1d\n" +
	"\n" +
	"subtask_id\x18\x01 \x01(\tR\tsubtaskId\x12'\n" +
	"\x04type\x18\x02 \x01(\x0e2\x13.cap.v1.SubtaskTypeR\x04type\x12%\n" +
	"\x0eagent_template\x18\x03 \x01(\tR\ragentTemplate\x12*\n" +
	"\x06status\x18\x04 \x01(\x0e2\x12.cap.v1.TaskStatusR\x06status\x12\x18\n" +
	"\asummary\x18\x05 \x01(\tR\asummary\x12.\n" +
	"\tartifacts\x18\x06 \x03(\v2\x10.cap.v1.ArtifactR\tartifacts\x12\x1d\n" +
	"\n" +
	"started_at\x18\a \x01(\tR\tstartedAt\x12!\n" +
	"\fcompleted_at\x18\b \x01(\tR\vcompletedAt\"\x95\x01\n" +
	"\bArtifact\x12\x1f\n" +
	"\vartifact_id\x18\x01 \x01(\tR\n" +
	"artifactId\x12(\n" +
	"\x04type\x18\x02 \x01(\x0e2\x14.cap.v1.ArtifactTypeR\x04type\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\x12\x12\n" +
	"\x04size\x18\x05 \x01(\x03R\x04size\"\xec\x01\n" +
	"\n" +
	"TaskResult\x12\x1d\n" +
	"\n" +
	"git_commit\x18\x01 \x01(\tR\tgitCommit\x12\x1d\n" +
	"\n" +
	"git_branch\x18\x02 \x01(\tR\tgitBranch\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary\x12,\n" +
	"\achanges\x18\x04 \x03(\v2\x12.cap.v1.FileChangeR\achanges\x123\n" +
	"\vtest_result\x18\x05 \x01(\v2\x12.cap.v1.TestResultR\n" +
	"testResult\x12#\n" +
	"\rquality_score\x18\x06 \x01(\x05R\fqualityScore\"\x8e\x01\n" +
	"\n" +
	"FileChange\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x120\n" +
	"\x06action\x18\x02 \x01(\x0e2\x18.cap.v1.FileChangeActionR\x06action\x12\x1c\n" +
	"\tadditions\x18\x03 \x01(\x05R\tadditions\x12\x1c\n" +
	"\tdeletions\x18\x04 \x01(\x05R\tdeletions\"n\n" +
	"\n" +
	"TestResult\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12\x16\n" +
	"\x06passed\x18\x02 \x01(\x05R\x06passed\x12\x16\n" +
	"\x06failed\x18\x03 \x01(\x05R\x06failed\x12\x1a\n" +
	"\bcoverage\x18\x04 \x01(\x05R\bcoverage\"t\n" +
	"\tTaskStats\x12\x1f\n" +
	"\vagents_used\x18\x01 \x01(\x05R\n" +
	"agentsUsed\x12\x1f\n" +
	"\vtokens_used\x18\x02 \x01(\x03R\n" +
	"tokensUsed\x12%\n" +
	"\x0eestimated_cost\x18\x03 \x01(\x01R\restimatedCost\"\x83\x01\n" +
	"\x10ListTasksRequest\x12*\n" +
	"\x06status\x18\x01 \x01(\x0e2\x12.cap.v1.TaskStatusR\x06status\x12\x12\n" +
	"\x04tags\x18\x02 \x03(\tR\x04tags\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"~\n" +
	"\x11ListTasksResponse\x12\"\n" +
	"\x05tasks\x18\x01 \x03(\v2\f.cap.v1.TaskR\x05tasks\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"o\n" +
	"\x11CancelTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12)\n" +
	"\x10terminate_agents\x18\x03 \x01(\bR\x0fterminateAgents\"\xbf\x01\n" +
	"\x12CancelTaskResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12*\n" +
	"\x06status\x18\x02 \x01(\x0e2\x12.cap.v1.TaskStatusR\x06status\x12+\n" +
	"\x11terminated_agents\x18\x03 \x03(\tR\x10terminatedAgents\x127\n" +
	"\x0epartial_result\x18\x04 \x01(\v2\x10.cap.v1.ArtifactR\rpartialResult\"\xbb\x01\n" +
	"\rDecideRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"subtask_id\x18\x02 \x01(\tR\tsubtaskId\x120\n" +
	"\bdecision\x18\x03 \x01(\x0e2\x14.cap.v1.UserDecisionR\bdecision\x12\x1a\n" +
	"\bfeedback\x18\x04 \x01(\tR\bfeedback\x12$\n" +
	"\rmodifications\x18\x05 \x01(\tR\rmodifications\"t\n" +
	"\x0eDecideResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"subtask_id\x18\x02 \x01(\tR\tsubtaskId\x12*\n" +
	"\x06status\x18\x03 \x01(\x0e2\x12.cap.v1.TaskStatusR\x06status\"N\n" +
	"\x12GetArtifactRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1f\n" +
	"\vartifact_id\x18\x02 \x01(\tR\n" +
	"artifactId\"\x80\x01\n" +
	"\x13GetArtifactResponse\x12,\n" +
	"\bartifact\x18\x01 \x01(\v2\x10.cap.v1.ArtifactR\bartifact\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\"F\n" +
	"\x0eGetDiffRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1b\n" +
	"\tmax_lines\x18\x02 \x01(\x05R\bmaxLines\"N\n" +
	"\x0fGetDiffResponse\x12\x12\n" +
	"\x04diff\x18\x01 \x01(\tR\x04diff\x12'\n" +
	"\x05stats\x18\x02 \x01(\v2\x11.cap.v1.DiffStatsR\x05stats\"]\n" +
	"\tDiffStats\x12\x14\n" +
	"\x05files\x18\x01 \x01(\x05R\x05files\x12\x1c\n" +
	"\tadditions\x18\x02 \x01(\x05R\tadditions\x12\x1c\n" +
	"\tdeletions\x18\x03 \x01(\x05R\tdeletions\"i\n" +
	"\x0fWaitTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x18\n" +
	"\atimeout\x18\x02 \x01(\x05R\atimeout\x12#\n" +
	"\rpoll_interval\x18\x03 \x01(\x05R\fpollInterval\"\xb4\x01\n" +
	"\x10WaitTaskResponse\x12 \n" +
	"\x04task\x18\x01 \x01(\v2\f.cap.v1.TaskR\x04task\x12\x1b\n" +
	"\ttimed_out\x18\x02 \x01(\bR\btimedOut\x123\n" +
	"\x15confirmation_required\x18\x03 \x01(\bR\x14confirmationRequired\x12,\n" +
	"\x12confirm_subtask_id\x18\x04 \x01(\tR\x10confirmSubtaskId*\x99\x02\n" +
	"\n" +
	"TaskStatus\x12\x1b\n" +
	"\x17TASK_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13TASK_STATUS_PENDING\x10\x01\x12\x1b\n" +
	"\x17TASK_STATUS_DECOMPOSING\x10\x02\x12\x1a\n" +
	"\x16TASK_STATUS_DISPATCHED\x10\x03\x12\x17\n" +
	"\x13TASK_STATUS_RUNNING\x10\x04\x12\x19\n" +
	"\x15TASK_STATUS_REVIEWING\x10\x05\x12\x1a\n" +
	"\x16TASK_STATUS_CONFIRMING\x10\x06\x12\x19\n" +
	"\x15TASK_STATUS_COMPLETED\x10\a\x12\x16\n" +
	"\x12TASK_STATUS_FAILED\x10\b\x12\x19\n" +
	"\x15TASK_STATUS_CANCELLED\x10\t*\xad\x01\n" +
	"\vSubtaskType\x12\x1c\n" +
	"\x18SUBTASK_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15SUBTASK_TYPE_ANALYSIS\x10\x01\x12\x17\n" +
	"\x13SUBTASK_TYPE_CODING\x10\x02\x12\x17\n" +
	"\x13SUBTASK_TYPE_REVIEW\x10\x03\x12\x18\n" +
	"\x14SUBTASK_TYPE_TESTING\x10\x04\x12\x19\n" +
	"\x15SUBTASK_TYPE_RESEARCH\x10\x05*\xb1\x01\n" +
	"\fArtifactType\x12\x1d\n" +
	"\x19ARTIFACT_TYPE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16ARTIFACT_TYPE_ANALYSIS\x10\x01\x12\x16\n" +
	"\x12ARTIFACT_TYPE_DIFF\x10\x02\x12\x1d\n" +
	"\x19ARTIFACT_TYPE_TEST_RESULT\x10\x03\x12\x18\n" +
	"\x14ARTIFACT_TYPE_REPORT\x10\x04\x12\x15\n" +
	"\x11ARTIFACT_TYPE_LOG\x10\x05*|\n" +
	"\fUserDecision\x12\x1d\n" +
	"\x19USER_DECISION_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15USER_DECISION_APPROVE\x10\x01\x12\x18\n" +
	"\x14USER_DECISION_REJECT\x10\x02\x12\x18\n" +
	"\x14USER_DECISION_MODIFY\x10\x03*m\n" +
	"\x0fCredentialsType\x12 \n" +
	"\x1cCREDENTIALS_TYPE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18CREDENTIALS_TYPE_SSH_KEY\x10\x01\x12\x1a\n" +
	"\x16CREDENTIALS_TYPE_TOKEN\x10\x02*\x95\x01\n" +
	"\x10FileChangeAction\x12\"\n" +
	"\x1eFILE_CHANGE_ACTION_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18FILE_CHANGE_ACTION_ADDED\x10\x01\x12\x1f\n" +
	"\x1bFILE_CHANGE_ACTION_MODIFIED\x10\x02\x12\x1e\n" +
	"\x1aFILE_CHANGE_ACTION_DELETED\x10\x032\x8c\x04\n" +
	"\vTaskService\x12A\n" +
	"\x06Submit\x12\x19.cap.v1.SubmitTaskRequest\x1a\x1a.cap.v1.SubmitTaskResponse\"\x00\x128\n" +
	"\x03Get\x12\x16.cap.v1.GetTaskRequest\x1a\x17.cap.v1.GetTaskResponse\"\x00\x12=\n" +
	"\x04List\x12\x18.cap.v1.ListTasksRequest\x1a\x19.cap.v1.ListTasksResponse\"\x00\x12A\n" +
	"\x06Cancel\x12\x19.cap.v1.CancelTaskRequest\x1a\x1a.cap.v1.CancelTaskResponse\"\x00\x129\n" +
	"\x06Decide\x12\x15.cap.v1.DecideRequest\x1a\x16.cap.v1.DecideResponse\"\x00\x12H\n" +
	"\vGetArtifact\x12\x1a.cap.v1.GetArtifactRequest\x1a\x1b.cap.v1.GetArtifactResponse\"\x00\x12<\n" +
	"\aGetDiff\x12\x16.cap.v1.GetDiffRequest\x1a\x17.cap.v1.GetDiffResponse\"\x00\x12;\n" +
	"\x04Wait\x12\x17.cap.v1.WaitTaskRequest\x1a\x18.cap.v1.WaitTaskResponse\"\x00B6Z4github.com/cloud-agent-platform/cap/api/cap/v1;capv1b\x06proto3"

var (
	file_task_proto_rawDescOnce sync.Once
	file_task_proto_rawDescData []byte
)

func file_task_proto_rawDescGZIP() []byte {
	file_task_proto_rawDescOnce.Do(func() {
		file_task_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_task_proto_rawDesc), len(file_task_proto_rawDesc)))
	})
	return file_task_proto_rawDescData
}

var file_task_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_task_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_task_proto_goTypes = []any{
	(TaskStatus)(0),             // 0: cap.v1.TaskStatus
	(SubtaskType)(0),            // 1: cap.v1.SubtaskType
	(ArtifactType)(0),           // 2: cap.v1.ArtifactType
	(UserDecision)(0),           // 3: cap.v1.UserDecision
	(CredentialsType)(0),        // 4: cap.v1.CredentialsType
	(FileChangeAction)(0),       // 5: cap.v1.FileChangeAction
	(*Repository)(nil),          // 6: cap.v1.Repository
	(*Credentials)(nil),         // 7: cap.v1.Credentials
	(*AgentHint)(nil),           // 8: cap.v1.AgentHint
	(*SubmitTaskRequest)(nil),   // 9: cap.v1.SubmitTaskRequest
	(*SubmitTaskResponse)(nil),  // 10: cap.v1.SubmitTaskResponse
	(*GetTaskRequest)(nil),      // 11: cap.v1.GetTaskRequest
	(*GetTaskResponse)(nil),     // 12: cap.v1.GetTaskResponse
	(*Task)(nil),                // 13: cap.v1.Task
	(*Subtask)(nil),             // 14: cap.v1.Subtask
	(*Artifact)(nil),            // 15: cap.v1.Artifact
	(*TaskResult)(nil),          // 16: cap.v1.TaskResult
	(*FileChange)(nil),          // 17: cap.v1.FileChange
	(*TestResult)(nil),          // 18: cap.v1.TestResult
	(*TaskStats)(nil),           // 19: cap.v1.TaskStats
	(*ListTasksRequest)(nil),    // 20: cap.v1.ListTasksRequest
	(*ListTasksResponse)(nil),   // 21: cap.v1.ListTasksResponse
	(*CancelTaskRequest)(nil),   // 22: cap.v1.CancelTaskRequest
	(*CancelTaskResponse)(nil),  // 23: cap.v1.CancelTaskResponse
	(*DecideRequest)(nil),       // 24: cap.v1.DecideRequest
	(*DecideResponse)(nil),      // 25: cap.v1.DecideResponse
	(*GetArtifactRequest)(nil),  // 26: cap.v1.GetArtifactRequest
	(*GetArtifactResponse)(nil), // 27: cap.v1.GetArtifactResponse
	(*GetDiffRequest)(nil),      // 28: cap.v1.GetDiffRequest
	(*GetDiffResponse)(nil),     // 29: cap.v1.GetDiffResponse
	(*DiffStats)(nil),           // 30: cap.v1.DiffStats
	(*WaitTaskRequest)(nil),     // 31: cap.v1.WaitTaskRequest
	(*WaitTaskResponse)(nil),    // 32: cap.v1.WaitTaskResponse
}
var file_task_proto_depIdxs = []int32{
	7,  // 0: cap.v1.Repository.credentials:type_name -> cap.v1.Credentials
	4,  // 1: cap.v1.Credentials.type:type_name -> cap.v1.CredentialsType
	6,  // 2: cap.v1.SubmitTaskRequest.repository:type_name -> cap.v1.Repository
	8,  // 3: cap.v1.SubmitTaskRequest.agent_hint:type_name -> cap.v1.AgentHint
	0,  // 4: cap.v1.SubmitTaskResponse.status:type_name -> cap.v1.TaskStatus
	13, // 5: cap.v1.GetTaskResponse.task:type_name -> cap.v1.Task
	0,  // 6: cap.v1.Task.status:type_name -> cap.v1.TaskStatus
	14, // 7: cap.v1.Task.subtasks:type_name -> cap.v1.Subtask
	16, // 8: cap.v1.Task.result:type_name -> cap.v1.TaskResult
	19, // 9: cap.v1.Task.stats:type_name -> cap.v1.TaskStats
	1,  // 10: cap.v1.Subtask.type:type_name -> cap.v1.SubtaskType
	0,  // 11: cap.v1.Subtask.status:type_name -> cap.v1.TaskStatus
	15, // 12: cap.v1.Subtask.artifacts:type_name -> cap.v1.Artifact
	2,  // 13: cap.v1.Artifact.type:type_name -> cap.v1.ArtifactType
	17, // 14: cap.v1.TaskResult.changes:type_name -> cap.v1.FileChange
	18, // 15: cap.v1.TaskResult.test_result:type_name -> cap.v1.TestResult
	5,  // 16: cap.v1.FileChange.action:type_name -> cap.v1.FileChangeAction
	0,  // 17: cap.v1.ListTasksRequest.status:type_name -> cap.v1.TaskStatus
	13, // 18: cap.v1.ListTasksResponse.tasks:type_name -> cap.v1.Task
	0,  // 19: cap.v1.CancelTaskResponse.status:type_name -> cap.v1.TaskStatus
	15, // 20: cap.v1.CancelTaskResponse.partial_result:type_name -> cap.v1.Artifact
	3,  // 21: cap.v1.DecideRequest.decision:type_name -> cap.v1.UserDecision
	0,  // 22: cap.v1.DecideResponse.status:type_name -> cap.v1.TaskStatus
	15, // 23: cap.v1.GetArtifactResponse.artifact:type_name -> cap.v1.Artifact
	30, // 24: cap.v1.GetDiffResponse.stats:type_name -> cap.v1.DiffStats
	13, // 25: cap.v1.WaitTaskResponse.task:type_name -> cap.v1.Task
	9,  // 26: cap.v1.TaskService.Submit:input_type -> cap.v1.SubmitTaskRequest
	11, // 27: cap.v1.TaskService.Get:input_type -> cap.v1.GetTaskRequest
	20, // 28: cap.v1.TaskService.List:input_type -> cap.v1.ListTasksRequest
	22, // 29: cap.v1.TaskService.Cancel:input_type -> cap.v1.CancelTaskRequest
	24, // 30: cap.v1.TaskService.Decide:input_type -> cap.v1.DecideRequest
	26, // 31: cap.v1.TaskService.GetArtifact:input_type -> cap.v1.GetArtifactRequest
	28, // 32: cap.v1.TaskService.GetDiff:input_type -> cap.v1.GetDiffRequest
	31, // 33: cap.v1.TaskService.Wait:input_type -> cap.v1.WaitTaskRequest
	10, // 34: cap.v1.TaskService.Submit:output_type -> cap.v1.SubmitTaskResponse
	12, // 35: cap.v1.TaskService.Get:output_type -> cap.v1.GetTaskResponse
	21, // 36: cap.v1.TaskService.List:output_type -> cap.v1.ListTasksResponse
	23, // 37: cap.v1.TaskService.Cancel:output_type -> cap.v1.CancelTaskResponse
	25, // 38: cap.v1.TaskService.Decide:output_type -> cap.v1.DecideResponse
	27, // 39: cap.v1.TaskService.GetArtifact:output_type -> cap.v1.GetArtifactResponse
	29, // 40: cap.v1.TaskService.GetDiff:output_type -> cap.v1.GetDiffResponse
	32, // 41: cap.v1.TaskService.Wait:output_type -> cap.v1.WaitTaskResponse
	34, // [34:42] is the sub-list for method output_type
	26, // [26:34] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_task_proto_init() }
func file_task_proto_init() {
	if File_task_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_task_proto_rawDesc), len(file_task_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_task_proto_goTypes,
		DependencyIndexes: file_task_proto_depIdxs,
		EnumInfos:         file_task_proto_enumTypes,
		MessageInfos:      file_task_proto_msgTypes,
	}.Build()
	File_task_proto = out.File
	file_task_proto_goTypes = nil
	file_task_proto_depIdxs = nil
}
